version: '3.1'

services:
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: passwd
      MYSQL_DATABASE: task
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - "3306:3306"